package com.ali.coffeehub.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemConfigEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemConfigEntityAllPropertiesEquals(SystemConfigEntity expected, SystemConfigEntity actual) {
        assertSystemConfigEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemConfigEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemConfigEntityAllUpdatablePropertiesEquals(SystemConfigEntity expected, SystemConfigEntity actual) {
        assertSystemConfigEntityUpdatableFieldsEquals(expected, actual);
        assertSystemConfigEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemConfigEntityAutoGeneratedPropertiesEquals(SystemConfigEntity expected, SystemConfigEntity actual) {
        assertThat(expected)
            .as("Verify SystemConfigEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemConfigEntityUpdatableFieldsEquals(SystemConfigEntity expected, SystemConfigEntity actual) {
        assertThat(expected)
            .as("Verify SystemConfigEntity relevant properties")
            .satisfies(e -> assertThat(e.getKey()).as("check key").isEqualTo(actual.getKey()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getModuleName()).as("check moduleName").isEqualTo(actual.getModuleName()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemConfigEntityUpdatableRelationshipsEquals(SystemConfigEntity expected, SystemConfigEntity actual) {
        // empty method
    }
}
