package com.ali.coffeehub.article.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArticleReactionEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleReactionEntityAllPropertiesEquals(ArticleReactionEntity expected, ArticleReactionEntity actual) {
        assertArticleReactionEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertArticleReactionEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleReactionEntityAllUpdatablePropertiesEquals(
        ArticleReactionEntity expected,
        ArticleReactionEntity actual
    ) {
        assertArticleReactionEntityUpdatableFieldsEquals(expected, actual);
        assertArticleReactionEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleReactionEntityAutoGeneratedPropertiesEquals(
        ArticleReactionEntity expected,
        ArticleReactionEntity actual
    ) {
        assertThat(expected)
            .as("Verify ArticleReactionEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleReactionEntityUpdatableFieldsEquals(ArticleReactionEntity expected, ArticleReactionEntity actual) {
        assertThat(expected)
            .as("Verify ArticleReactionEntity relevant properties")
            .satisfies(e -> assertThat(e.getAticleId()).as("check aticleId").isEqualTo(actual.getAticleId()))
            .satisfies(e -> assertThat(e.getUserId()).as("check userId").isEqualTo(actual.getUserId()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleReactionEntityUpdatableRelationshipsEquals(
        ArticleReactionEntity expected,
        ArticleReactionEntity actual
    ) {
        // empty method
    }
}
