package com.ali.coffeehub.article.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArticleStatisticEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleStatisticEntityAllPropertiesEquals(ArticleStatisticEntity expected, ArticleStatisticEntity actual) {
        assertArticleStatisticEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertArticleStatisticEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleStatisticEntityAllUpdatablePropertiesEquals(
        ArticleStatisticEntity expected,
        ArticleStatisticEntity actual
    ) {
        assertArticleStatisticEntityUpdatableFieldsEquals(expected, actual);
        assertArticleStatisticEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleStatisticEntityAutoGeneratedPropertiesEquals(
        ArticleStatisticEntity expected,
        ArticleStatisticEntity actual
    ) {
        assertThat(expected)
            .as("Verify ArticleStatisticEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleStatisticEntityUpdatableFieldsEquals(ArticleStatisticEntity expected, ArticleStatisticEntity actual) {
        assertThat(expected)
            .as("Verify ArticleStatisticEntity relevant properties")
            .satisfies(e -> assertThat(e.getAticleId()).as("check aticleId").isEqualTo(actual.getAticleId()))
            .satisfies(e -> assertThat(e.getViewCount()).as("check viewCount").isEqualTo(actual.getViewCount()))
            .satisfies(e -> assertThat(e.getLikeCount()).as("check likeCount").isEqualTo(actual.getLikeCount()))
            .satisfies(e -> assertThat(e.getCommentCount()).as("check commentCount").isEqualTo(actual.getCommentCount()))
            .satisfies(e -> assertThat(e.getAvgTimeSpent()).as("check avgTimeSpent").isEqualTo(actual.getAvgTimeSpent()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleStatisticEntityUpdatableRelationshipsEquals(
        ArticleStatisticEntity expected,
        ArticleStatisticEntity actual
    ) {
        // empty method
    }
}
