package com.ali.coffeehub.article.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArticleBodyEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleBodyEntityAllPropertiesEquals(ArticleBodyEntity expected, ArticleBodyEntity actual) {
        assertArticleBodyEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertArticleBodyEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleBodyEntityAllUpdatablePropertiesEquals(ArticleBodyEntity expected, ArticleBodyEntity actual) {
        assertArticleBodyEntityUpdatableFieldsEquals(expected, actual);
        assertArticleBodyEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleBodyEntityAutoGeneratedPropertiesEquals(ArticleBodyEntity expected, ArticleBodyEntity actual) {
        assertThat(expected)
            .as("Verify ArticleBodyEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleBodyEntityUpdatableFieldsEquals(ArticleBodyEntity expected, ArticleBodyEntity actual) {
        assertThat(expected)
            .as("Verify ArticleBodyEntity relevant properties")
            .satisfies(e -> assertThat(e.getBody()).as("check body").isEqualTo(actual.getBody()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleBodyEntityUpdatableRelationshipsEquals(ArticleBodyEntity expected, ArticleBodyEntity actual) {
        // empty method
    }
}
