package com.ali.coffeehub.cafeteria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CoffeeShopLocationEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoffeeShopLocationEntityAllPropertiesEquals(
        CoffeeShopLocationEntity expected,
        CoffeeShopLocationEntity actual
    ) {
        assertCoffeeShopLocationEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertCoffeeShopLocationEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoffeeShopLocationEntityAllUpdatablePropertiesEquals(
        CoffeeShopLocationEntity expected,
        CoffeeShopLocationEntity actual
    ) {
        assertCoffeeShopLocationEntityUpdatableFieldsEquals(expected, actual);
        assertCoffeeShopLocationEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoffeeShopLocationEntityAutoGeneratedPropertiesEquals(
        CoffeeShopLocationEntity expected,
        CoffeeShopLocationEntity actual
    ) {
        assertThat(expected)
            .as("Verify CoffeeShopLocationEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoffeeShopLocationEntityUpdatableFieldsEquals(
        CoffeeShopLocationEntity expected,
        CoffeeShopLocationEntity actual
    ) {
        assertThat(expected)
            .as("Verify CoffeeShopLocationEntity relevant properties")
            .satisfies(e -> assertThat(e.getCoffeeShopId()).as("check coffeeShopId").isEqualTo(actual.getCoffeeShopId()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()))
            .satisfies(e -> assertThat(e.getIsMainBranch()).as("check isMainBranch").isEqualTo(actual.getIsMainBranch()))
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoffeeShopLocationEntityUpdatableRelationshipsEquals(
        CoffeeShopLocationEntity expected,
        CoffeeShopLocationEntity actual
    ) {
        // empty method
    }
}
