package com.ali.coffeehub.brew.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConfigEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigEntityAllPropertiesEquals(ConfigEntity expected, ConfigEntity actual) {
        assertConfigEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertConfigEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigEntityAllUpdatablePropertiesEquals(ConfigEntity expected, ConfigEntity actual) {
        assertConfigEntityUpdatableFieldsEquals(expected, actual);
        assertConfigEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigEntityAutoGeneratedPropertiesEquals(ConfigEntity expected, ConfigEntity actual) {
        assertThat(expected)
            .as("Verify ConfigEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigEntityUpdatableFieldsEquals(ConfigEntity expected, ConfigEntity actual) {
        assertThat(expected)
            .as("Verify ConfigEntity relevant properties")
            .satisfies(e -> assertThat(e.getRecipeId()).as("check recipeId").isEqualTo(actual.getRecipeId()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigEntityUpdatableRelationshipsEquals(ConfigEntity expected, ConfigEntity actual) {
        // empty method
    }
}
