package com.ali.coffeehub.brew.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConfigValueEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigValueEntityAllPropertiesEquals(ConfigValueEntity expected, ConfigValueEntity actual) {
        assertConfigValueEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertConfigValueEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigValueEntityAllUpdatablePropertiesEquals(ConfigValueEntity expected, ConfigValueEntity actual) {
        assertConfigValueEntityUpdatableFieldsEquals(expected, actual);
        assertConfigValueEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigValueEntityAutoGeneratedPropertiesEquals(ConfigValueEntity expected, ConfigValueEntity actual) {
        assertThat(expected)
            .as("Verify ConfigValueEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigValueEntityUpdatableFieldsEquals(ConfigValueEntity expected, ConfigValueEntity actual) {
        assertThat(expected)
            .as("Verify ConfigValueEntity relevant properties")
            .satisfies(e -> assertThat(e.getConfigId()).as("check configId").isEqualTo(actual.getConfigId()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigValueEntityUpdatableRelationshipsEquals(ConfigValueEntity expected, ConfigValueEntity actual) {
        // empty method
    }
}
