package com.ali.coffeehub.brew.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StepEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepEntityAllPropertiesEquals(StepEntity expected, StepEntity actual) {
        assertStepEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertStepEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepEntityAllUpdatablePropertiesEquals(StepEntity expected, StepEntity actual) {
        assertStepEntityUpdatableFieldsEquals(expected, actual);
        assertStepEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepEntityAutoGeneratedPropertiesEquals(StepEntity expected, StepEntity actual) {
        assertThat(expected)
            .as("Verify StepEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepEntityUpdatableFieldsEquals(StepEntity expected, StepEntity actual) {
        assertThat(expected)
            .as("Verify StepEntity relevant properties")
            .satisfies(e -> assertThat(e.getBrewId()).as("check brewId").isEqualTo(actual.getBrewId()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDetail()).as("check detail").isEqualTo(actual.getDetail()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStepEntityUpdatableRelationshipsEquals(StepEntity expected, StepEntity actual) {
        // empty method
    }
}
