package com.ali.coffeehub.brew.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ToolEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToolEntityAllPropertiesEquals(ToolEntity expected, ToolEntity actual) {
        assertToolEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertToolEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToolEntityAllUpdatablePropertiesEquals(ToolEntity expected, ToolEntity actual) {
        assertToolEntityUpdatableFieldsEquals(expected, actual);
        assertToolEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToolEntityAutoGeneratedPropertiesEquals(ToolEntity expected, ToolEntity actual) {
        assertThat(expected)
            .as("Verify ToolEntity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToolEntityUpdatableFieldsEquals(ToolEntity expected, ToolEntity actual) {
        assertThat(expected)
            .as("Verify ToolEntity relevant properties")
            .satisfies(e -> assertThat(e.getBrewId()).as("check brewId").isEqualTo(actual.getBrewId()))
            .satisfies(e -> assertThat(e.getDetail()).as("check detail").isEqualTo(actual.getDetail()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToolEntityUpdatableRelationshipsEquals(ToolEntity expected, ToolEntity actual) {
        // empty method
    }
}
